### ISSUE TITLE
allow airlight to spread

### ISSUE THREAD

**Issue by S-S-X** [pandorabox-io/planet_mars#2]
Allow airlight to spread around and fix itself if airlight is gone because of jumpdrive used in area, something built in area or whatever reason that destroys airlight.

Maybe with abm nearby nodes dirt with grass / permafrost / trees or something like that.

**Comment by S-S-X** [comment]
maybe lbm could also work here as possibly cheaper alternative.

**Comment by S-S-X** [comment]
actually now that I checked it seems that there's already abm for this, it was just so slow that I didn't notice it at all.
closing this as invalid issue.

**Comment by BuckarooBanzay** [comment]
fwiw: lighting in minetest is hacky at best and the current "airlight" solution is sadly the best i could find...
